package com.example.governance.records;

import com.example.governance.retention.RetentionPolicy;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.OffsetDateTime;
import java.util.UUID;

// Maps the Flyway-created records table to a Java object.
// IMPORTANT: The field mappings here should stay aligned with V1__create_records_schema.sql.
@Entity
@Table(name = "records")
public class GovernanceRecord {

	// Primary key generated by Hibernate as a UUID instead of a database sequence.
	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	// updatable = false means application code should never change the primary key after insert.
	@Column(nullable = false, updatable = false)
	private UUID id;

	// Business ID from an external system; the database also has a unique constraint for this.
	@NotBlank
	@Size(max = 120)
	@Column(name = "external_id", nullable = false, length = 120)
	private String externalId;

	// Human-readable record title.
	@NotBlank
	@Size(max = 255)
	@Column(nullable = false)
	private String name;

	// Current lifecycle state of the record.
	@NotNull
	// IMPORTANT: STRING stores ACTIVE/ARCHIVED/etc.; ORDINAL would store numbers and is fragile.
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, length = 40)
	private RecordStatus status;

	// A record may have a retention policy, but the database allows it to be empty.
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "retention_policy_id")
	private RetentionPolicy retentionPolicy;

	// insertable/updatable false means PostgreSQL owns this timestamp default.
	@Column(name = "created_at", nullable = false, insertable = false, updatable = false)
	private OffsetDateTime createdAt;

	// PostgreSQL sets this on insert; later phases can update it when records change.
	@Column(name = "updated_at", nullable = false, insertable = false)
	private OffsetDateTime updatedAt;

	// Future retention phase: when this record should expire.
	@Column(name = "expires_at")
	private OffsetDateTime expiresAt;

	// Future archive phase: when this record was archived.
	@Column(name = "archived_at")
	private OffsetDateTime archivedAt;

	// Future purge phase: when this record was purged.
	@Column(name = "purged_at")
	private OffsetDateTime purgedAt;

	// JPA requires a no-argument constructor so it can create entities when reading from the database.
	protected GovernanceRecord() {
	}

	// Application constructor used by the service and tests when creating a new record.
	public GovernanceRecord(String externalId, String name, RecordStatus status, RetentionPolicy retentionPolicy) {
		this.externalId = externalId;
		this.name = name;
		this.status = status;
		this.retentionPolicy = retentionPolicy;
	}

	// Getters expose entity data without adding setters that could bypass service rules.
	public UUID getId() {
		return id;
	}

	public String getExternalId() {
		return externalId;
	}

	public String getName() {
		return name;
	}

	public RecordStatus getStatus() {
		return status;
	}

	public RetentionPolicy getRetentionPolicy() {
		return retentionPolicy;
	}

	// API responses need only the policy ID, not the whole RetentionPolicy object.
	public UUID getRetentionPolicyId() {
		return retentionPolicy == null ? null : retentionPolicy.getId();
	}

	public OffsetDateTime getCreatedAt() {
		return createdAt;
	}

	public OffsetDateTime getUpdatedAt() {
		return updatedAt;
	}

	public OffsetDateTime getExpiresAt() {
		return expiresAt;
	}

	public OffsetDateTime getArchivedAt() {
		return archivedAt;
	}

	public OffsetDateTime getPurgedAt() {
		return purgedAt;
	}
}
